use("Recipes");

db.recipes.insertMany([
  {
    title: "Tacos de pollo con salsa de aguacate",
    description: "Tacos crujientes con pollo sazonado y salsa cremosa de aguacate.",
    ingredients: ["pollo", "tortillas", "aguacate", "lechuga", "tomate", "limón"],
    category: "comida rápida",
    imageUrl: "https://example.com/tacos.jpg",
    difficulty: "fácil",
  },
  {
    title: "Pasta al pesto con tomates cherry",
    description: "Pasta ligera y sabrosa con salsa pesto casera y tomates frescos.",
    ingredients: ["pasta", "albahaca", "piñones", "aceite de oliva", "parmesano", "tomates cherry"],
    category: "pasta",
    imageUrl: "https://example.com/pasta-pesto.jpg",
    difficulty: "medio",
  },
  {
    title: "Sopa de lentejas con verduras",
    description: "Sopa nutritiva y reconfortante, perfecta para días fríos.",
    ingredients: ["lentejas", "zanahoria", "apio", "cebolla", "ajo", "tomate", "caldo"],
    category: "sopas",
    imageUrl: "https://example.com/sopa-lentejas.jpg",
    difficulty: "fácil",
  },
  {
    title: "Pizza margarita casera",
    description: "Clásica pizza con salsa de tomate, mozzarella y albahaca fresca.",
    ingredients: ["masa de pizza", "tomate", "mozzarella", "albahaca", "aceite de oliva"],
    category: "pizza",
    imageUrl: "https://example.com/pizza.jpg",
    difficulty: "medio",
  },
  {
    title: "Burrito de carne y frijoles",
    description: "Burrito consistente con carne, frijoles y verduras frescas.",
    ingredients: ["tortilla", "carne", "frijoles", "lechuga", "tomate", "queso"],
    category: "comida rápida",
    imageUrl: "https://example.com/burrito.jpg",
    difficulty: "medio",
  },
  {
    title: "Ensalada de garbanzos y atún",
    description: "Ensalada proteica y fresca, perfecta para el almuerzo.",
    ingredients: ["garbanzos", "atún", "tomate", "pepino", "aceite de oliva", "limón"],
    category: "ensaladas",
    imageUrl: "https://example.com/ensalada-garbanzos.jpg",
    difficulty: "fácil",
  },
  {
    title: "Crema de calabaza con jengibre",
    description: "Sopa cremosa y aromática, ideal para entradas elegantes.",
    ingredients: ["calabaza", "cebolla", "ajo", "jengibre", "caldo", "nata"],
    category: "sopas",
    imageUrl: "https://example.com/crema-calabaza.jpg",
    difficulty: "medio",
  },
  {
    title: "Pollo al curry con arroz basmati",
    description: "Plato exótico y sabroso, con salsa cremosa de curry.",
    ingredients: ["pollo", "curry", "arroz basmati", "cebolla", "leche de coco", "aceite"],
    category: "platos principales",
    imageUrl: "https://example.com/pollo-curry.jpg",
    difficulty: "medio",
  },
  {
    title: "Galletas de avena y pasas",
    description: "Galletas saludables, crujientes por fuera y suaves por dentro.",
    ingredients: ["avena", "harina", "mantequilla", "azúcar", "huevos", "pasas"],
    category: "postres",
    imageUrl: "https://example.com/galletas-avena.jpg",
    difficulty: "fácil",
  },
  {
    title: "Batido de fresa y plátano",
    description: "Bebida refrescante y energética para cualquier momento del día.",
    ingredients: ["fresas", "plátano", "leche", "yogur", "miel"],
    category: "bebidas",
    imageUrl: "https://example.com/batido-fresa.jpg",
    difficulty: "fácil",
  },
  {
    title: "Hamburguesa vegetariana con garbanzos",
    description: "Hamburguesa saludable con garbanzos y verduras frescas.",
    ingredients: ["garbanzos", "pan de hamburguesa", "lechuga", "tomate", "cebolla", "especias"],
    category: "comida rápida",
    imageUrl: "https://example.com/hamburguesa-veg.jpg",
    difficulty: "medio",
  },
  {
    title: "Risotto de champiñones y parmesano",
    description: "Risotto cremoso y elegante, ideal para cenas especiales.",
    ingredients: ["arroz arborio", "champiñones", "cebolla", "caldo", "parmesano", "mantequilla"],
    category: "platos principales",
    imageUrl: "https://example.com/risotto.jpg",
    difficulty: "difícil",
  },
  {
    title: "Smoothie verde detox",
    description: "Bebida saludable que ayuda a desintoxicar y revitalizar.",
    ingredients: ["espinaca", "pepino", "manzana verde", "apio", "limón", "agua"],
    category: "bebidas",
    imageUrl: "https://example.com/smoothie-verde.jpg",
    difficulty: "fácil",
  },
  {
    title: "Tarta de manzana clásica",
    description: "Postre tradicional con manzanas caramelizadas y masa crujiente.",
    ingredients: ["manzanas", "harina", "mantequilla", "azúcar", "canela", "huevo"],
    category: "postres",
    imageUrl: "https://example.com/tarta-manzana.jpg",
    difficulty: "medio",
  },
  {
    title: "Wrap de pavo y verduras",
    description: "Wrap ligero y nutritivo, perfecto para llevar al trabajo.",
    ingredients: ["tortilla", "pavo", "lechuga", "tomate", "zanahoria", "mayonesa ligera"],
    category: "comida rápida",
    imageUrl: "https://example.com/wrap-pavo.jpg",
    difficulty: "fácil",
  }
]);
